Converted to python3 and solved some bugs
mkesicki/excel_validator pull request #16
Opened 2020-11-13 20:33 UTC by JohnElmasry

I converted the code into a python3 compatible code. Also a bug has been solved when a cell breaks more than one validation rule. For example, Cell H4 in my proposed excel file has an error of conditional and datatype. The old code used to crash over this cell. In this pull request this bug has been handled.

2020-11-13 23:24 UTC, mkesicki requested changes

2020-11-13 23:24 UTC, mkesicki commented on excel_validator.py
> +                # if value bysawy awl cell fe el header
??

2020-11-13 23:24 UTC, mkesicki commented on excel_validator.py
> +                # if value bysawy awl cell fe el header
??

2020-11-13 23:24 UTC, mkesicki commented on excel_validator.py
> +                    #Saffar el Header
??

2020-11-13 23:24 UTC, mkesicki commented on excel_validator.py
> +#results !=True and equal None " File Kbeer "
these 3 lines can be removed

2020-11-13 23:24 UTC, mkesicki commented on excel_validator.py
> +
these lines can be removed

2020-11-13 23:24 UTC, mkesicki commented on validate.bat
> +pause
now will be hardcoded vale to file name, btw orginal version with temp value also looks fishy

2020-11-13 23:28 UTC, mkesicki commented
@JohnElmasry , thank you for PR. I think readme file should be updated also ;)

2020-11-14 11:38 UTC, JohnElmasry commented
Hello, Thank you for reaching out, and thanks for the program

Kindly find edited code

On Sat, Nov 14, 2020 at 1:28 AM Michał Kęsicki <notifications@github.com>
wrote:

> @JohnElmasry <https://github.com/JohnElmasry> , thank you for PR. I think
> readme file should be updated also ;)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mkesicki/excel_validator/pull/16#issuecomment-727083367>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOHCNMAHVYQCV7O4UJ3WQXLSPW6KNANCNFSM4TVAWKXQ>
> .
>

2020-11-14 13:21 UTC, merged